apiVersion: apps/v1
kind: Deployment
metadata:
  name: lanchonete
  labels:
    app: lanchonete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lanchonete
  template:
    metadata:
      labels:
        app: lanchonete
    spec:
      containers:
        - name: lanchonete
          image: lucaslemec/techchallenger-lanchonete-app:1.0
          ports:
            - containerPort: 8080